# Lab 1: CIFAR10 Challenge

**CIFAR10** (http://www.cs.toronto.edu/~kriz/cifar.html) is one of the most famous ML data sets. 

## Data
* 32x32 color images
* in 10 classes
* 50k training images
* 10k test images



<img src="https://production-media.paperswithcode.com/datasets/CIFAR-10-0000000431-b71f61c0_U5n3Glr.jpg" width=700>

In [1]:
#get data
from keras.datasets import cifar10
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

In [2]:
#traindata: 50k 32X32 rgb images
X_train.shape

(50000, 32, 32, 3)

In [3]:
X_train

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [4]:
#labels
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

## Task: build the best classifier (with feature extration) using the methods you know from ML1+2
* work in small teams (2-4)
* use NumPy pre-processing, feature extraction and hyer-parameter tuning in Scikit-Learn
* no Neural Networks! 
* best test F1-Score after 90min winns! 

**First Try out**

**Imports**

In [5]:
import numpy as np
import sklearn as sk

from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier

**Preprocessing**

In [6]:
X_train.shape

(50000, 32, 32, 3)

In [7]:
X_train.shape[0]

50000

In [8]:
t2_train_X = np.sum(X_train, axis=(1, 2))

t2_test_X = np.sum(X_test, axis=(1, 2))

In [9]:
t3_train_X = np.sum(X_train[:, 11:21, 11:21, :], axis=(1, 2))

t3_test_X = np.sum(X_test[:, 11:21, 11:21, :], axis=(1, 2))

In [10]:
X_train[:, 11:21, 11:21, :].shape

(50000, 10, 10, 3)

In [11]:
np.sum(X_train, axis=(1, 2))

array([[144594, 107622,  65574],
       [133324, 133494, 133609],
       [136688, 138396, 135767],
       ...,
       [ 84511, 112282, 125884],
       [166067, 172886, 181577],
       [142083, 132707, 130346]], dtype=uint64)

In [19]:
t4_train_X = X_train[:, 11:21, 11:21, :].flatten().reshape((X_train.shape[0], -1))

t4_test_X = X_test[:, 11:21, 11:21, :].flatten().reshape((X_test.shape[0], -1))

In [12]:
amount = X_train.shape[0]

try_train_X = X_train[0:amount, :]
try_train_y = y_train[0:amount, :]

try_test_X = X_test[0:amount, :]
try_test_y = y_test[0:amount, :]

In [13]:
t_train_X = try_train_X.flatten().reshape((try_train_X.shape[0], -1))
t_train_y = try_train_y.flatten().reshape((try_train_y.shape[0], -1))

t_test_X = try_test_X.flatten().reshape((try_test_X.shape[0], -1))
t_test_y = try_test_y.flatten().reshape((try_test_y.shape[0], -1))

**Modelling**

Data flattet + not to much data

In [14]:
# from sklearn.svm import SVC

# clf = sk.svm.SVC()
# clf.fit(t_train_X, t_train_y)

# f1_score(t_test_y, clf.predict(t_test_X), average="macro")

In [18]:
clf = RandomForestClassifier()
clf.fit(t_train_X, t_train_y)

res = f1_score(t_test_y, clf.predict(t_test_X), average="macro")
print(f"Best Result = {round(res, 2)}")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


Best Result = 0.47


In [22]:
# same with 10x10
clf = RandomForestClassifier()
clf.fit(t4_train_X, y_train)

f1_score(y_test, clf.predict(t4_test_X), average="macro")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


0.35090479204594416

RGB Sum of all Pictures

In [16]:
clf = RandomForestClassifier()
clf.fit(t2_train_X, y_train)

f1_score(y_test, clf.predict(t2_test_X), average="macro")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


0.21678950318912663

Reduction to 10x10 -> pixels of center

In [17]:
clf = RandomForestClassifier()
clf.fit(t3_train_X, y_train)

f1_score(y_test, clf.predict(t3_test_X), average="macro")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


0.20298598875693413