# Numpy exercises

HINT: use the Numpy documentations
* [NumPy User Guide](https://numpy.org/doc/1.22/user/index.html#user)
* [NumPy API](https://numpy.org/doc/1.22/reference/index.html#reference)

In [1]:

  import numpy as np

#### 1) Create a null vector of size 10 (★☆☆)

In [3]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 2) Print the memory size in bytes of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 3) Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 4) Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5) Reverse a vector (first element becomes last) (★☆☆)

In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 6) Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7) Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [10]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 8) Create a 3x3 identity matrix (★☆☆)

In [11]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 9) Create a 3x3x3 array with random values (★☆☆)

In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.07156054 0.42200768 0.5816812 ]
  [0.47645631 0.07352644 0.49628096]
  [0.68551075 0.61633533 0.68955908]]

 [[0.42675683 0.93123148 0.64263023]
  [0.62074361 0.12939413 0.09398736]
  [0.19403232 0.86208457 0.0244165 ]]

 [[0.16167514 0.68491965 0.32636814]
  [0.5060693  0.79447999 0.13253234]
  [0.7157131  0.90797999 0.19673651]]]


#### 10) Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.007525540492307692 0.9973583592447723


#### 11) Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.453501784707476


#### 12) Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 13) How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 14) Predict (before executig) the results of the following expressions? (★☆☆)

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 15) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 16) Create a 8x8 matrix and fill it with a checkerboard (0,1) pattern (★☆☆)

In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 17) Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 18) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 19) Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 20. How to find common values between two arrays? (★☆☆)

In [30]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[4 5 6 8]


#### 21) How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 22) Extract the integer part of a random array (★★☆)

In [36]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[0. 4. 7. 2. 3. 4. 7. 4. 3. 9.]
[0. 4. 7. 2. 3. 4. 7. 4. 3. 9.]
[0. 4. 7. 2. 3. 4. 7. 4. 3. 9.]
[0 4 7 2 3 4 7 4 3 9]
[0. 4. 7. 2. 3. 4. 7. 4. 3. 9.]


#### 23) Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 24) Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 25) Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 26) Create a random vector of size 10 and sort it (★★☆)

In [40]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.03817887 0.04802085 0.15332298 0.23315999 0.31533443 0.36261581
 0.80745364 0.845371   0.90540275 0.98557637]


#### 27) Consider two random array A and B, check if they are equal (★★☆)

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 28) Make an array immutable (read-only) (★★☆)

In [43]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 29) Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.27379013 0.77398508 0.14142044 0.2608233  0.79177202 0.38945906
 0.68547022 0.53853571 0.38706058 0.        ]


#### 30) How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 31) randomly place 3 elements in a 2D array? (★★☆)

In [57]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 1. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 32) Subtract the mean of each row of a matrix (★★☆)

In [58]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.28492484  0.14205536 -0.35648869 -0.11476651  0.10421304 -0.18625435
   0.4540789   0.25794395  0.12260677 -0.13846365]
 [-0.1832807   0.05600344  0.07188816 -0.09568362 -0.21077799  0.1043757
   0.06658078 -0.23403791  0.30489638  0.12003576]
 [ 0.02092794  0.11491452  0.38646451 -0.34823297  0.20873512  0.04860952
  -0.09658252 -0.47156327 -0.15178146  0.28850862]
 [ 0.24403427  0.17402431 -0.24875324  0.19467245 -0.56642408 -0.21511991
   0.17037612  0.35751604 -0.51651716  0.4061912 ]
 [-0.33445746 -0.07621975 -0.17057265 -0.16875847  0.13436368  0.17217339
  -0.28304379  0.62701034  0.14587425 -0.04636955]]


#### 33) sort an array by the 1st column? (★★☆)

In [59]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 9 5]
 [4 3 4]
 [9 3 5]]
[[4 3 4]
 [9 3 5]
 [3 9 5]]


#### 34) Find the nearest value from a given value in an array (★★☆)

In [61]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5292066356758519


#### 35) Considering two arrays with shape (1,3) and (3,1): to compute their sum using an iterator (★★☆)

In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 36) find the most frequent value in an array

In [83]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 37) Given a two dimensional array, extract unique rows (★★★)

In [101]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))


# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 1]]
