# Recalling Numpy Array Slicing and Indexing

Credit: Images taken from: https://towardsdatascience.com/advanced-numpy-master-stride-tricks-with-25-illustrated-exercises-923a9393ab20

In [1]:
import numpy as np

In [30]:
#create array
x = np.asarray(range(1,26), np.int8).reshape(5,5)

In [3]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]], dtype=int8)

## Slice first 3 elements

<img src="IMG/np01.png">

In [5]:
x[0,:3]

array([1, 2, 3], dtype=int8)

##  Slice first 8 elements

<img src="IMG/np02.png">

In [12]:
x.flatten()[:8]

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int8)

## Skip every other element

<img src="IMG/np03.png">

In [13]:
x[0,::2]

array([1, 3, 5], dtype=int8)

## Slice first column

<img src="IMG/np04.png">

In [14]:
x[:4,0]

array([ 1,  6, 11, 16], dtype=int8)

## Slice a diagonal

<img src="IMG/np05.png">

In [15]:
x.diagonal()


array([ 1,  7, 13, 19, 25], dtype=int8)

## Repeat the first element

<img src="IMG/np06.png">

In [31]:
np.tile((x[0,0]),(1,5))

array([[1, 1, 1, 1, 1]], dtype=int8)

In [16]:
np.broadcast_to(x[0,0], (5,))

array([1, 1, 1, 1, 1], dtype=int8)

## Simple 2D slicing

<img src="IMG/np07.png">

In [17]:
x[:3,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]], dtype=int8)

## Slice a zigzag 

<img src="IMG/np08.png">

In [32]:
#using stride_tricks -> https://numpy.org/doc/stable/reference/generated/numpy.lib.stride_tricks.as_strided.html
import numpy as np
from numpy.lib.stride_tricks import as_strided
x = np.asarray(range(1,26), np.int32).reshape(5,5)
as_strided(x, shape=(4,2), strides=(48,8))


array([[        1,         3],
       [       13,        15],
       [       25,        49],
       [859255094,        33]], dtype=int32)

## Sparse slicing

<img src="IMG/np09.png">

In [21]:
x[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]], dtype=int8)

## Transpose a 2D array

<img src="IMG/np10.png">

In [22]:
x[:3,:3].T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13]], dtype=int8)

## Repeat the first column 4 times


<img src="IMG/np11.png">

In [34]:
np.broadcast_to(x[:,0,None], (5,4))


array([[ 1,  1,  1,  1],
       [ 6,  6,  6,  6],
       [11, 11, 11, 11],
       [16, 16, 16, 16],
       [21, 21, 21, 21]], dtype=int32)

## Reshape 1D array to 2D array

<img src="IMG/np12.png">

In [25]:
x = np.asarray(range(1,13), np.int64)
x.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Collapse an axis from a 3D array

<img src="IMG/np13.png">

In [28]:
x = np.asarray(range(1,13), np.int8).reshape(3,2,2)
print(x)
x.reshape(3,4)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int8)